name: CI

# To satisfy required status checks for docs-only changes, configure jobs that match those in ci.yaml that
# always return true.
on:
  pull_request:
    branches:
    - main
    - 'release-*'
    paths:
      - "docs/**"
      - "**/*.md"
      - ".github/ISSUE_TEMPLATE/*"
      - ".goreleaser.yaml"

jobs:
  go-test-e2e:
    name: go-test-e2e
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No build required"'

  go-test:
    name: go-test
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No build required"'
